### ISSUE TITLE
Error in analysis due to pandas bug

### ISSUE THREAD

**Issue by ghost** [TomAugspurger/modern-pandas#30]
@TomAugspurger, I found https://github.com/pandas-dev/pandas/issues/22509 by chasing down an error in part 2. You use the broken form of `groupby().transform('rank')` in "Chaining methods", to create this graph:

![flights](https://tomaugspurger.github.io/modern_2_method_chaining_files/modern_2_method_chaining_11_0.png)

If you use `dep_time.rank()` instead you get the correct result
 
![flights](https://user-images.githubusercontent.com/51503352/59143526-b6300200-89bb-11e9-86df-18ec538e972d.png)

**Comment by pilkibun** [comment]
To illustrate:
```python
In [34]: df=pd.DataFrame(dict(price=[10,10,20,20,30,30],cost=(100,200,300,400,500,600)))
    ...: df
Out[34]: 
   price  cost
0     10   100
1     10   200
2     20   300
3     20   400
4     30   500
5     30   600

# wrong
In [35]: df.groupby('price').cost.transform('rank')
Out[35]: 
0    1.0
1    1.0
2    2.0
3    2.0
4    1.0
5    1.0
Name: cost, dtype: float64

# correct
In [36]: df.groupby('price').cost.rank()
Out[36]: 
0    1.0
1    2.0
2    1.0
3    2.0
4    1.0
5    2.0
Name: cost, dtype: float64
```

**Comment by pilkibun** [comment]
To illustrate:
```python
In [34]: df=pd.DataFrame(dict(price=[10,10,20,20,30,30],cost=(100,200,300,400,500,600)))
    ...: df
Out[34]: 
   price  cost
0     10   100
1     10   200
2     20   300
3     20   400
4     30   500
5     30   600

# wrong
In [35]: df.groupby('price').cost.transform('rank')
Out[35]: 
0    1.0
1    1.0
2    2.0
3    2.0
4    1.0
5    1.0
Name: cost, dtype: float64

# correct
In [36]: df.groupby('price').cost.rank()
Out[36]: 
0    1.0
1    2.0
2    1.0
3    2.0
4    1.0
5    2.0
Name: cost, dtype: float64
```

**Comment by ghost** [comment]
See https://github.com/pandas-dev/pandas/issues/22509#issuecomment-500982426 for comparison of `rank()` and currently broken `transform('rank')`.

**Comment by ghost** [comment]
ping @TomAugspurger, have you seen this yet? you're so responsive on pandas, but this has been here for a few days, just wondering.

**Comment by TomAugspurger** [comment]
Seen it. Won't have time to look for a while though.
