### ISSUE TITLE
Unable to open file on github or offline

### ISSUE THREAD

**Issue by frankherfert** [TomAugspurger/modern-pandas#6]
Github just says there was a problem with the file, Jupyter provides the following error message:
Unreadable Notebook: 
..\modern_2_method_chaining.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="en...',)

**Comment by TomAugspurger** [comment]
What version of the notebook to you have (`jupyter notebook --version`)? It renders fine [here](http://nbviewer.jupyter.org/github/TomAugspurger/modern-pandas/blob/master/modern_2_method_chaining.ipynb) and locally, so perhaps you have an older version?

**Comment by TomAugspurger** [comment]
Closing this for now, let me know if updating your notebook version doesn't fix it for you.

**Comment by frankherfert** [comment]
It works for me on nbviewer but github seems to have trouble with its viewer (all your other notebooks work fine).
My jupyter is on the latest version. Thanks for you help.
